
-- SOCIAL TRAITS

INSERT INTO feat_or_trait (name, description, type) VALUES ('Criminal', 'You’ve got a record, as well as some unscrupulous contacts.', 'social_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Debt', 'Starting money is tripled, but you have to pay it back some time.', 'social_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Dependent', 'You have a staunch ally, but they always need something from you.', 'social_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Highborn', 'Some people find you snooty, but you fit in well with high society.', 'social_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('I Know a Guy', 'You always run into someone you know, whether you want to or not.', 'social_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Indigent', 'The slums are home, and it can be hard to fit in anywhere else.', 'social_trait');


-- PHYSICAL TRAITS

-- Positive Traits

INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Ambidexterity', 'You negate your -2 off-hand penalty.', 'physical_trait', 2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Beautiful', '+2 Charisma when sexuality is relevant.', 'physical_trait', 4);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Double-Jointed', 'You receive a +2 bonuses for escaping from bonds.', 'physical_trait', 1);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Focused', 'You gain a +2 bonus any time you take a 10.', 'physical_trait', 2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Giant', '+1 Size Category', 'physical_trait', 2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Hardened', '+2 Vitality vs. Fear.', 'physical_trait', 2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Hardy Metabolism', '+2 Fortitude vs. Poisons, Drugs and Alcohol.', 'physical_trait', 2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('High Education', '+2 in one Academia Focus area', 'physical_trait', 2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Night Vision', 'Lowers Darkness penalties by 2.', 'physical_trait', 2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Photographic Memory', 'If you saw it, you can remember it.', 'physical_trait', 4);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Quick Healer', 'You can roll Natural Healing in half the normal time.', 'physical_trait', 4);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Will to Live', 'You can always re-roll a Death Save once.', 'physical_trait', 2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Strong Constitution", "You can ignore your first Level of Fatigue.", "physical_trait", 4);

-- Negative Traits

INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('All Thumbs', 'A mishap occurs on a Fate 1 or 2 when using technology.', 'physical_trait', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Bad Luck', 'A mishap occurs on a Fate 1 or 2, and no Benefit on a 6.', 'physical_trait', -8);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Clumsy', 'A mishap occurs on a Fate 1 or 2 on movement-related rolls.', 'physical_trait', -4);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Dwarf', '-1 Size Category', 'physical_trait', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Incompetent', 'You receive another -2 bonus to Untrained Unique Skills.', 'physical_trait', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Insomniac', 'You suffer a -2 to penalty to all rolls related to resting.', 'physical_trait', -1);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Low Pain Tolerance', 'You receive another -1 Wound penalty, starting at Bloodied.', 'physical_trait', -3);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Skittish', '-2 Vitality vs. Fear, additional when Surprised.', 'physical_trait', -3);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Slow Healer', 'You roll Natural Healing after twice the normal time.', 'physical_trait', -3);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Tongue-Tied', 'A mishap occurs on a Fate 1 or 2 on speech-related rolls.', 'physical_trait', -4);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Unmistakable', 'Without a proper disguise, you’re easy to spot in a crowd.', 'physical_trait', -1);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Weak Metabolism', '-2 Fortitude vs. Poisons, Drugs and Alcohol.', 'physical_trait', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Frail Constitution", "You are Unconscious after 3 Levels of Fatigue instead of 4.", "physical_trait", -3);


-- COMPELLING ACTIONS

INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Addicted', 'You have a vice that you can’t seem to escape. You may choose one vice when this taken (i.e. alcohol, tobacco, gambling, sex, etc.), and may take this multiple times for multiple vices at the GM’s discretion. Any time this vice is available to you, you must succeed a minimum Vitality roll DL 10 to resist. If you go a session without your vice, you receive a cumulative -1 penalty to Morale, up to -4 maximum.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Ascetic', 'You view the accumulation of wealth and enjoyment of luxuries as bad for the soul. As such, you will avoid these things, and must succeed a minimum Vitality roll DL 10 in order to earn money you don’t need and enjoy activities or items that could be considered a distraction from suffering, indulgent or unnecessary. You will also never shy away from the harder or more dangerous path if it has the potential to produce the best out come.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Curious', 'You have an extremely difficult time resisting unknown, interesting and new situations. If you ever wish to avoid such a situation a minimum Vitality roll DL 10 is required.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('For the Clan', 'If the honor or prowess of you or your people is ever questioned or insulted, you are always obligated to defend your honor. This may not always lead to a fight, but if the offender is already considered an enemy, it often will. Resisting this desire is always a minimum Vitality roll DL 10, unless engaging would somehow further sully your honor or your people’s.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Fuck Authority', 'You don’t like being told what to do, how to act, or what they can and cannot say. When this happens, you will often reject the command or suggestion simply for the sake of maintaining your sense of autonomy. To resist this desire requires a minimum Vitality roll DL 10 unless it would put your lifeat risk.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Honest', 'You value truth and honesty, and will rarely lie, especially to a friend or ally. If you ever wish to lie, except in clearly dire situations, you must first succeed a minimum Vitality roll DL 10.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Honor-bound', 'If you ever make a promise, you will do your best to never break it. This is doubly so if the recipient is close friend or ally, or someone who has helped you in some way. If you wish to go back on your word, a minimum Vitality roll DL 10 is necessary.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Pacifist', 'You value peace and harmony above all else and will do all you can to avoid violent conflict, or even aggressive conversation. To resist this desire requires a minimum Vitality roll DL 10 unless your life, or someone close to you, would be in danger.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Protector of The Wild', 'You view yourself as a guardian of the wild places. If you ever witness abuse, misuse or wanton destruction of wild places or wild animals, you are obliged to intercede. If you wish to resist this compulsion, a minimum Vitality roll DL 10 is necessary.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Show Me the Money', 'Anytime you have an opportunity to barter, gamble or otherwise make money without significant risk, you must succeed a Vitality roll of a minimum of DL 10 to resist the urge.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Solemn Oath', 'You have made a promise to an important individual or organization or have sworn vengeance against a person or organization. The oath must be agreed upon with the GM when this is taken and may take multiple Oath’s at the GM’s discretion. You must pursue this Oath whenever possible, and anything that could be a distraction from fulfilling your Oath, or is in conflict with your Oath, cannot be undertaken without a minimum Vitality roll of DL 10. This is Compelling Action is removed when the Oath is fulfilled.', 'compelling_action', -2);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ('Warrior\'s Code', 'You value honor in battle above most things. As a result, you will rarely attack an Unaware or Unarmed opponent, and will attempt to stop or intercede in a fight you see as dishonorable. If you wish to resist this compulsion, a minimum Vitality roll DL 10 is necessary.', 'compelling_action', -2);


-- MORALE TRAITS

INSERT INTO feat_or_trait (name, description, type) VALUES ('Celebrity', 'Positive State: You gained 2 Renown last Session; Negative State: You didn’t gain any Renown last Session', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Extrovert', 'Positive State: A new NPC really likes you; Negative State: You didn’t hang out with any NPC friends', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Fancypants', 'Positive State: You had a new luxury experience this Session; Negative State: No luxury experience last Session', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Gamer', 'Positive State: You won some kind of game this Session; Negative State: You lost a game last Session', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Glutton', 'Positive State: All of your meals were excessive; Negative State: None of your meals were decent last Session', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Merrymaker', 'Positive State: You got drunk this Session; Negative State: You didn’t have any drinks last Session', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Miracle', 'Positive State: You used no Alignment Bonuses last Session; Negative State: You used all Alignment Bonuses last Session', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Pennypincher', 'Positive State: You have more than 800 credits/8 Gold/$40; Negative State: You have less than 400 credits/4 Gold/$20', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Philanderer', 'Positive State: You had 1 new sexual encounter this Session; Negative State: No new encounters last Session', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Rover', 'Positive State: You went to a new planet/region this Session; Negative State: You stayed in one place last Session', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Spendthrift', 'Positive State: You have less than 20 credits/4 Silver/$1; Negative State: You have more than 200 credits/2 Gold/$10', 'morale_trait');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Wunderkind', 'Positive State: You succeeded all rolls last Session; Negative State: You failed 2 or more rolls last Session', 'morale_trait');


-- PROFESSIONS

INSERT INTO feat_or_trait (name, description, type) VALUES ('Archaeologist', 'You have studied and taught ancient civilizations and cultures of South America at world renowned Universities and are one of the best in your field. You can identify artifacts and structures of all known societies in South America and can make educated guesses about the purpose and nature of unknown ones. You can translate ancient writing from all known past civilizations in South American and may attempt translation of unknown ones. Archaeology must be learned under Intellect.', 'profession');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Botanist/Herbalist', 'Whether through academia or indigenous knowledge, you know the plants of the Amazon better than most. You can identify any Amazonian plants with a DL 10 or less, and as long as you are in or near the Amazon, you can find any plant from the Drug/Poison Ingredients Lists once per day of travel without making a roll. Additionally, even if fail a roll or you are outside of the Amazon, a DL 15 will identify likely properties of any plants you encounter. Herbalism can be learned under Intuition or Intellect.', 'profession');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Cartographer', 'The Cartographer is a master of maps and geography. You can create detailed maps of any area you have travelled through with impressive accuracy (DL 14). Additionally, if you have a map of an unexplored area, you can never become lost and can also roll Cartography without a map to attempt to find your direction (DL 10). Cartography can be learned under Awareness or Innovation.', 'profession');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Ex-Military', 'You were a career soldier for many years, until that one mission went terribly wrong. Now you make your way as a hired gun, and you know guns well. You ignore Misfire on all weapons and reduce Accuracy penalties by 1. You also begin the game Trained in Demolitions and Tactics.', 'profession');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Philanthropist', 'Somehow you got filthy rich, and you’ve spent most of your money funding the pursuit of the Lost City. Because of your deep pockets and fame, you have bought and befriended people everywhere. Any time you visit a new town or city you may declare a relationship with an inhabitant. This can be someone of your creation, with GM approval, or you can declare a relationship to any pre-existing NPC. The nature and quality of the relationship is still at the GM’s discretion. Even after you have done this, you can always name-drop with anyone, which will provide anywhere from a +4 to -4 to any Charisma roll. The bonus/penalty will be unknown to you until after the roll. Additionally, as long as you have access to a city with a bank, you can withdraw $100/day.', 'profession');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Street Rat', 'You’ve never had a family to look out for you, and the roof over your head was the sky more often than not. But it made you resilient and creative, and you know how to get along with the wrong kind of people. Any time you are in a town or city you can make an Intuition or Awareness roll to find black market or illegal activities, and these people will never be outright hostile toward you as long as you are alone. You also begin the game Trained in Stealth and either Security OR Sleight of Hand.', 'profession');


-- SOCIAL BACKGROUNDS

INSERT INTO feat_or_trait (name, description, type) VALUES ('Nobility', 'You had a posh upbringing that some might consider pampered and indulgent. You’re well-read, well-educated and well-travelled. You gain 2 Bonus Skill Points to place in Diplomacy, Academia or Language Focuses. You are Literate and gain 2d4 additional starting funds.', 'social_background');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Courtier', 'You weren’t rich, but you lived a wealthy life on the coattails of others, mainly by kissing the right asses and knowing how to manipulate your superiors. You gain 3 Bonus Skill Points to place in Diplomacy, Seduce or Sense Motive Focuses. You are Literate and gain 1d4 additional starting funds.', 'social_background');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Merchant', 'You came from a Merchant family, which meant you worked hard and often to keep yourselves above the peasant masses. You understand people and business well and travelled the world often buying, selling and trading. You gain 3 Bonus Skill Points to place in Appraise, Barter or Languages Focuses. You are Literate and gain 1d4 additional starting funds.', 'social_background');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Scholar', 'You trained extensively with the most educated minds of your city, tirelessly transcribing texts and reading more books than even the wealthiest minds have consumed. You gain 4 Bonus Skill Points to place in Academia, Culture, Languages or Religion. You are Literate.', 'social_background');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Soldier', 'You spent some time enlisted in the military, defending your home. You’ve seen your share of battle, but you’re ready for new adventures and some real freedom. You gain a +1 Bonus in Shoot and Attack. You must choose a specific Weapon Type for each Focus and you may apply the Bonus after initial Skill Points have been spent. You are Illiterate.', 'social_background');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Craftsman', 'You made stuff, and you made it well enough to make a decent living, but never well enough to really get noticed. You gain a +2 Bonus in a single Craft Item Focus and you may apply the Bonus after initial Skill Points have been spent. You are Illiterate.', 'social_background');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Peasant', 'You broke your body to keep the rich fat and barely enough food in your own belly. You’ve survived the hardest of times and come out strong for it. You gain 5 Bonus Skill Points to place in Lift, Resist Disease or Craft Item Focuses. You are Illiterate and lose 1d4 starting funds.', 'social_background');
INSERT INTO feat_or_trait (name, description, type) VALUES ('Street Urchin', 'You never had a real home and survived off of wit, luck and a lot of illegal activity. You’re a survivor and as resourceful as they come. You gain 2 Bonus Skill Points to place in Disguise, Search, Listen or Run Focuses and gain the Security, Stealth or Sleight of Hand Unique Skill for free. You are Illiterate and lose 2d4 starting funds.', 'social_background');
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Professor/Researcher", "Whether in the University, museums or research institutes, you were once well-respected by the few people that knew your name. Unfortunately, your “extra-curricular” research got you into trouble and you've found yourself in need of alternate employment. You may choose one eclectic, academic area as a Focus under Intellect (i.e. American Folklore, Cryptozoology, etc.). This Focus is treated as if you have Eclectic Knowledge if you ever fail a roll, and if you also have Eclectic Knowledge, you double your normal percentile chance. You also gain the Esoteric Knowledge Skill.", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Prospector", "You travelled west to make your fortune, and things went well for a while, but eventually, your home on the coast called you back for better things. Spending so much time underground had its benefits though. You always know direction in the dark, or when underground, and can identify likely mining areas on a detailed map (even if you have never visited the are) by making an appropriate Attribute roll of DL 10 maximum. You can identify any ores or precious metals, without rolling, and begin with either the Demolitions OR Engineering Skill.", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Frontiersman", "You've made a living staking claims, mapping out new territories, hunting, and trapping. The wilderness is your home and you generally prefer it to city-life, but things get lonesome out west, and you know you're destined for bigger things. You can create detailed maps of any area you have travelled through with a DL 14. Additionally, if you have a map of an area, you can never become delayed or lost. You gain the Survival Skill.", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Cowboy", "You made your living on the range, and you had a way with Horses beyond mere training and commands. But you were at it all for a bit too long, and the tedium got to you. Now it's time to mosey on. Any time you encounter a Horse, wild or domestic, you can attempt to Tame it using your Intuition or Allure. The DL is determined by the GM, based on your relationship to the Horse as well as the Horses' relationship to their owner (if they have one). The maximum DL is 14. You gain the Ride Animal Skill and may use Train Animal on Horses only.", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Medicine Wo/Man", "Through your indigenous knowledge, you know the plants of America better than most. You've chosen to work with the white man because you know that greater evils are at play, and besides... maybe not every white man is a monster. You may choose one region: Mountain, Desert, Coastal or Forest. You can identify any plants with a maximum DL of 10 in your chosen region. Additionally, even if you fail a roll or you are outside of your chosen region, a DL 14 will identify likely properties of any plants you encounter. You also gain the First Aid Skill.", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Old Money", "Because of your deep pockets and fame, you have befriended (and bribed) people everywhere, but your family (or business) has been trying to cut you out. It's about time to make a name for yourself on your terms. Any time you visit a new town or city you may declare a relationship with an inhabitant. This can be someone of your own creation (with GM approval), or you can declare a relationship to a pre-existing NPC. The quality and nature of the relationship is still at the GM's discretion, but it will never be detrimental to you. Additionally, as long as you have access to a city with a bank, you can withdraw up to $50/week and double your starting funds.", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Definitely Illegal", "The frontier was the perfect place to make a living any way possible, and you took full advantage. But now it's time to do something bigger. You know your way around the seedy underbelly of American black markets, illegal businesses, criminal syndicates. Anytime you are in a new town, you can make an appropriate Attribute check to locate such businesses and activities, with a maximum DL of 10. You are fluent in the slang and culture of this world and will not be treated hostilely or with suspicion from such people unless you act in a contradictory way, or as the result of Fate. You gain the Security Skill AND any other Unique Skill of your choosing. You also have Bounty on your head (so watch your back).", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Snake-oil Salesman", "Everyone's got to make a living, and you can give people a good show and some hope in a bottle, who are you to argue? But not everything is smoke and mirrors, and you're determined to find the truth behind the rumors you've heard about otherworldly forces at work in the world - if for no other reason than to monetize real magic. Because you've travelled so much, you know people everywhere, and most of them never want to see you again. Anytime you visit a town or city, you must use a Motivator Bonus to declare yourself unknown, otherwise your bad reputation will precede you. You gain the Sleight of Hand AND Perform Skill.", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Soldier/Lawman", "You were a career gunman for many years, and you've seen your fair share of combat and shoot-outs. Eventually, you grew tired of the life you built and ventured out to find new excitement, and maybe make a name for yourself. You know guns better than your own body and may ignore Misfire on all weapons and reduce Accuracy penalties by 1. Unfortunately, you made a lot of enemies along the way, and you are wanted dead or alive by an outlaw gang. You gain the Tactics AND Ride Animal Skills.", "social_background", 0);
INSERT INTO feat_or_trait (name, description, type, cost) VALUES ("Freed Slave", "You were born into slavery but managed to escape from bondage and find freedom in the North. Life still hasn't been easy, but a positive mindset and a cunning mind have kept you safe and content, and you've found a few Northerners you think can trust. Unfortunately, it's also impossible to travel into Confederate lands without a white escort. Negative Morale Effects are reduced 1 Level (i.e. you suffer no effects until -4, and can never suffer the standard -8 Morale Effect). You also gain the Stealth AND Survival Skills.", "social_background", 0);


-- RACE TRAITS

  insert into feat_or_trait (name,description,type,cost) values ("Iron Soul","Asgari add half their Soma Bonus to their Caster Level for Soma Magic only.","race_trait",0);
  insert into feat_or_trait (name,description,type,cost) values ("Master of the Wild","Vanir add half their Avani Bonus to their Caster Level for Avani Magic only.","race_trait",0);
  insert into feat_or_trait (name,description,type,cost) values ("Mentalist","Pangu add half their Nous Bonus to their Caster Level for Nous Magic only.","race_trait",0);
  insert into feat_or_trait (name,description,type,cost) values ("Energy Weaver","Alfir add half their Ka Bonus to their Caster Level for Ka Magic only.","race_trait",0);

